---
title: "Individual 1"
author: "Mitchell Kazin"
date: "9/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
  library(ggplot2)
```

```{r}
  happy <- readRDS("HAPPY.rds")
  names(happy) = tolower(names(happy))
  head(happy)
```

```{r}
  happy[happy=="NA"] <- NA
  happy[happy=="DK"] <- NA
  happy[happy=="IAP"] <- NA
```

```{r}
  happy[happy=="89 OR OLDER"] <- 89
  happy$age <- as.numeric(happy$age)
  happy$happy <- factor(happy$happy, levels = c("NOT TOO HAPPY", "PRETTY HAPPY", "VERY HAPPY"))
  levels(happy$happy)
  happy$sex <- factor(happy$sex, levels = c("FEMALE", "MALE"))
  levels(happy$sex)
  happy$marital <- factor(happy$marital, levels = c("NEVER MARRIED", "MARRIED", "SEPARATED", "DIVORCED", "WIDOWED"))
  levels(happy$marital)
  happy$degree <- factor(happy$degree, levels = c("LT HIGH SCHOOL", "HIGH SCHOOL", "JUNIOR COLLEGE", "BACHELOR", "GRADUATE"))
  levels(happy$degree)
  happy$finrela <- factor(happy$finrela, levels = c("FAR BELOW AVERAGE", "BELOW AVERAGE", "AVERAGE", "ABOVE AVERAGE", "FAR ABOVE AVERAGE"))
  levels(happy$finrela)
  happy$health <- factor(happy$health, levels = c("POOR", "FAIR", "GOOD", "EXCELLENT"))
  levels(happy$health)
  happy$partyid <- factor(happy$partyid, levels = c("STRONG DEMOCRAT", "NOT STR DEMOCRAT",  "IND,NEAR DEM", "INDEPENDENT", "IND,NEAR REP", "NOT STR REPUBLICAN", "STRONG REPUBLICAN", "OTHER PARTY"))
  levels(happy$partyid)
```